language: node_js
node_js:
  - 8

env:
  global:
    - GITHUB_REPO="github.com/WaiChungWong/weather-forecast"

after_success: |
  if [ -n "$GITHUB_TOKEN" ]; then
    git checkout master
    npm run build
    mv build demo
    rm -rf build
    git add .
    git -c user.name="TravisCI" -c user.email="travis@travis-ci.org" commit -m "deploy demo"
    git push -f -q "https://$GITHUB_TOKEN@${GITHUB_REPO}.git" master
  fi
