export const IDLE = "IDLE";
export const LOADING = "LOADING";
export const SEARCH_FOUND = "SEARCH_FOUND";
export const SEARCH_NOT_FOUND = "SEARCH_NOT_FOUND";
export const SEARCH_FAILED = "SEARCH_FAILED";
export const TEMPERATURE_UNIT_CHANGE = "TEMPERATURE_UNIT_CHANGE";
export const WIND_SPEED_UNIT_CHANGE = "WIND_SPEED_UNIT_CHANGE";
